server:
  port: 8082
spring:
  application:
    name: learn
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        prefetch: 1
        concurrency: 5
        acknowledge-mode: manual
    publisher-confirm-type: correlated
  redis:
    host: 127.0.0.1
    port: 6379
    password: tailgrass
